# Generated by Django 4.1.1 on 2023-05-21 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processed_image',
            name='input_image_model',
        ),
        migrations.AddField(
            model_name='input_image',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processed_image',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
